/**
 * Design System Tokens — runtime object.
 *
 * AUTO-GENERATED by scripts/sync-design-system.mjs — DO NOT EDIT BY HAND.
 * Edit src/design-system/tokens/*.json, then run: npm run sync:design-system
 *
 * Maps every design-system CSS variable to a typed JS value. Import directly
 * (not via the barrel) when inside the design-system package to avoid circular refs.
 */

export const tokens = {
  color: {
    gray: {
      50: 'var(--ds-color-gray-50)',
      100: 'var(--ds-color-gray-100)',
      200: 'var(--ds-color-gray-200)',
      300: 'var(--ds-color-gray-300)',
      400: 'var(--ds-color-gray-400)',
      500: 'var(--ds-color-gray-500)',
      600: 'var(--ds-color-gray-600)',
      700: 'var(--ds-color-gray-700)',
      800: 'var(--ds-color-gray-800)',
      900: 'var(--ds-color-gray-900)',
      950: 'var(--ds-color-gray-950)',
    },
    purple: {
      50: 'var(--ds-color-purple-50)',
      100: 'var(--ds-color-purple-100)',
      200: 'var(--ds-color-purple-200)',
      300: 'var(--ds-color-purple-300)',
      400: 'var(--ds-color-purple-400)',
      500: 'var(--ds-color-purple-500)',
      600: 'var(--ds-color-purple-600)',
      700: 'var(--ds-color-purple-700)',
      800: 'var(--ds-color-purple-800)',
      900: 'var(--ds-color-purple-900)',
      950: 'var(--ds-color-purple-950)',
    },
    blue: {
      50: 'var(--ds-color-blue-50)',
      100: 'var(--ds-color-blue-100)',
      200: 'var(--ds-color-blue-200)',
      300: 'var(--ds-color-blue-300)',
      400: 'var(--ds-color-blue-400)',
      500: 'var(--ds-color-blue-500)',
      600: 'var(--ds-color-blue-600)',
      700: 'var(--ds-color-blue-700)',
      800: 'var(--ds-color-blue-800)',
      900: 'var(--ds-color-blue-900)',
      950: 'var(--ds-color-blue-950)',
    },
    green: {
      50: 'var(--ds-color-green-50)',
      100: 'var(--ds-color-green-100)',
      200: 'var(--ds-color-green-200)',
      300: 'var(--ds-color-green-300)',
      400: 'var(--ds-color-green-400)',
      500: 'var(--ds-color-green-500)',
      600: 'var(--ds-color-green-600)',
      700: 'var(--ds-color-green-700)',
      800: 'var(--ds-color-green-800)',
      900: 'var(--ds-color-green-900)',
      950: 'var(--ds-color-green-950)',
    },
    red: {
      50: 'var(--ds-color-red-50)',
      100: 'var(--ds-color-red-100)',
      200: 'var(--ds-color-red-200)',
      300: 'var(--ds-color-red-300)',
      400: 'var(--ds-color-red-400)',
      500: 'var(--ds-color-red-500)',
      600: 'var(--ds-color-red-600)',
      700: 'var(--ds-color-red-700)',
      800: 'var(--ds-color-red-800)',
      900: 'var(--ds-color-red-900)',
      950: 'var(--ds-color-red-950)',
    },
    amber: {
      50: 'var(--ds-color-amber-50)',
      100: 'var(--ds-color-amber-100)',
      200: 'var(--ds-color-amber-200)',
      300: 'var(--ds-color-amber-300)',
      400: 'var(--ds-color-amber-400)',
      500: 'var(--ds-color-amber-500)',
      600: 'var(--ds-color-amber-600)',
      700: 'var(--ds-color-amber-700)',
      800: 'var(--ds-color-amber-800)',
      900: 'var(--ds-color-amber-900)',
      950: 'var(--ds-color-amber-950)',
    },
    orange: {
      50: 'var(--ds-color-orange-50)',
      100: 'var(--ds-color-orange-100)',
      200: 'var(--ds-color-orange-200)',
      300: 'var(--ds-color-orange-300)',
      400: 'var(--ds-color-orange-400)',
      500: 'var(--ds-color-orange-500)',
      600: 'var(--ds-color-orange-600)',
      700: 'var(--ds-color-orange-700)',
      800: 'var(--ds-color-orange-800)',
      900: 'var(--ds-color-orange-900)',
      950: 'var(--ds-color-orange-950)',
    },
    emerald: {
      50: 'var(--ds-color-emerald-50)',
      100: 'var(--ds-color-emerald-100)',
      200: 'var(--ds-color-emerald-200)',
      300: 'var(--ds-color-emerald-300)',
      400: 'var(--ds-color-emerald-400)',
      500: 'var(--ds-color-emerald-500)',
      600: 'var(--ds-color-emerald-600)',
      700: 'var(--ds-color-emerald-700)',
      800: 'var(--ds-color-emerald-800)',
      900: 'var(--ds-color-emerald-900)',
      950: 'var(--ds-color-emerald-950)',
    },
    white: '#ffffff',
    black: '#000000',
  },
  semantic: {
    bg: {
      default: 'var(--ds-bg)',
      subtle: 'var(--ds-bg-subtle)',
      muted: 'var(--ds-bg-muted)',
      hover: 'var(--ds-bg-hover)',
      elevated: 'var(--ds-bg-elevated)',
    },
    fg: {
      default: 'var(--ds-fg)',
      muted: 'var(--ds-fg-muted)',
      subtle: 'var(--ds-fg-subtle)',
      onPrimary: 'var(--ds-fg-on-primary)',
    },
    border: {
      default: 'var(--ds-border)',
      muted: 'var(--ds-border-muted)',
      strong: 'var(--ds-border-strong)',
    },
    primary: {
      default: 'var(--ds-primary)',
      hover: 'var(--ds-primary-hover)',
      subtle: 'var(--ds-primary-subtle)',
      fg: 'var(--ds-primary-fg)',
    },
    success: {
      default: 'var(--ds-success)',
      hover: 'var(--ds-success-hover)',
      subtle: 'var(--ds-success-subtle)',
      fg: 'var(--ds-success-fg)',
    },
    warning: {
      default: 'var(--ds-warning)',
      hover: 'var(--ds-warning-hover)',
      subtle: 'var(--ds-warning-subtle)',
      fg: 'var(--ds-warning-fg)',
    },
    danger: {
      default: 'var(--ds-danger)',
      hover: 'var(--ds-danger-hover)',
      subtle: 'var(--ds-danger-subtle)',
      fg: 'var(--ds-danger-fg)',
    },
    info: {
      default: 'var(--ds-info)',
      hover: 'var(--ds-info-hover)',
      subtle: 'var(--ds-info-subtle)',
      fg: 'var(--ds-info-fg)',
    },
  },
  space: {
    0: 'var(--ds-space-0)',
    1: 'var(--ds-space-1)',
    2: 'var(--ds-space-2)',
    3: 'var(--ds-space-3)',
    4: 'var(--ds-space-4)',
    5: 'var(--ds-space-5)',
    6: 'var(--ds-space-6)',
    8: 'var(--ds-space-8)',
    10: 'var(--ds-space-10)',
    12: 'var(--ds-space-12)',
    16: 'var(--ds-space-16)',
    20: 'var(--ds-space-20)',
    24: 'var(--ds-space-24)',
    32: 'var(--ds-space-32)',
    40: 'var(--ds-space-40)',
    48: 'var(--ds-space-48)',
    64: 'var(--ds-space-64)',
  },
  font: {
    family: {
      sans: 'var(--ds-font-family-sans)',
      mono: 'var(--ds-font-family-mono)',
    },
    weight: {
      normal: 'var(--ds-font-weight-normal)',
      medium: 'var(--ds-font-weight-medium)',
      semibold: 'var(--ds-font-weight-semibold)',
      bold: 'var(--ds-font-weight-bold)',
    },
    size: {
      '2xs': 'var(--ds-font-size-2xs)',
      xs: 'var(--ds-font-size-xs)',
      sm: 'var(--ds-font-size-sm)',
      md: 'var(--ds-font-size-md)',
      base: 'var(--ds-font-size-base)',
      lg: 'var(--ds-font-size-lg)',
      xl: 'var(--ds-font-size-xl)',
      '2xl': 'var(--ds-font-size-2xl)',
      '3xl': 'var(--ds-font-size-3xl)',
      '4xl': 'var(--ds-font-size-4xl)',
      '5xl': 'var(--ds-font-size-5xl)',
      'display-sm': 'var(--ds-font-size-display-sm)',
      display: 'var(--ds-font-size-display)',
      'display-lg': 'var(--ds-font-size-display-lg)',
    },
    lineHeight: {
      tight: 'var(--ds-line-height-tight)',
      snug: 'var(--ds-line-height-snug)',
      normal: 'var(--ds-line-height-normal)',
      relaxed: 'var(--ds-line-height-relaxed)',
      loose: 'var(--ds-line-height-loose)',
    },
  },
  tracking: {
    tighter: 'var(--ds-tracking-tighter)',
    tight: 'var(--ds-tracking-tight)',
    normal: 'var(--ds-tracking-normal)',
    wide: 'var(--ds-tracking-wide)',
    wider: 'var(--ds-tracking-wider)',
    widest: 'var(--ds-tracking-widest)',
  },
  radius: {
    none: 'var(--ds-radius-none)',
    sm: 'var(--ds-radius-sm)',
    md: 'var(--ds-radius-md)',
    lg: 'var(--ds-radius-lg)',
    xl: 'var(--ds-radius-xl)',
    '2xl': 'var(--ds-radius-2xl)',
    full: 'var(--ds-radius-full)',
  },
  shadow: {
    xs: 'var(--ds-shadow-xs)',
    sm: 'var(--ds-shadow-sm)',
    md: 'var(--ds-shadow-md)',
    lg: 'var(--ds-shadow-lg)',
    xl: 'var(--ds-shadow-xl)',
    '2xl': 'var(--ds-shadow-2xl)',
    none: 'var(--ds-shadow-none)',
    card: 'var(--ds-shadow-card)',
    'card-hover': 'var(--ds-shadow-card-hover)',
    'card-hover-accent': 'var(--ds-shadow-card-hover-accent)',
  },
  zIndex: {
    base: 'var(--ds-z-base)',
    dropdown: 'var(--ds-z-dropdown)',
    sticky: 'var(--ds-z-sticky)',
    overlay: 'var(--ds-z-overlay)',
    modal: 'var(--ds-z-modal)',
    popover: 'var(--ds-z-popover)',
    toast: 'var(--ds-z-toast)',
    tooltip: 'var(--ds-z-tooltip)',
  },
  motion: {
    duration: {
      fast: 'var(--ds-duration-fast)',
      base: 'var(--ds-duration-base)',
      slow: 'var(--ds-duration-slow)',
    },
    easing: {
      standard: 'var(--ds-ease-standard)',
      accelerate: 'var(--ds-ease-accelerate)',
      decelerate: 'var(--ds-ease-decelerate)',
    },
  },
  breakpoint: {
    sm: 'var(--ds-bp-sm)',
    md: 'var(--ds-bp-md)',
    lg: 'var(--ds-bp-lg)',
    xl: 'var(--ds-bp-xl)',
    '2xl': 'var(--ds-bp-2xl)',
  },
  typography: {
    'heading-xs': {
      fontFamily: 'var(--ds-font-family-sans)',
      fontSize: 'var(--ds-font-size-lg)',
      fontWeight: 'var(--ds-font-weight-semibold)',
      lineHeight: 'var(--ds-line-height-tight)',
    },
    'heading-sm': {
      fontFamily: 'var(--ds-font-family-sans)',
      fontSize: 'var(--ds-font-size-xl)',
      fontWeight: 'var(--ds-font-weight-semibold)',
      lineHeight: 'var(--ds-line-height-tight)',
    },
    'heading-md': {
      fontFamily: 'var(--ds-font-family-sans)',
      fontSize: 'var(--ds-font-size-2xl)',
      fontWeight: 'var(--ds-font-weight-semibold)',
      lineHeight: 'var(--ds-line-height-tight)',
    },
    'heading-lg': {
      fontFamily: 'var(--ds-font-family-sans)',
      fontSize: 'var(--ds-font-size-3xl)',
      fontWeight: 'var(--ds-font-weight-bold)',
      lineHeight: 'var(--ds-line-height-tight)',
    },
    'heading-xl': {
      fontFamily: 'var(--ds-font-family-sans)',
      fontSize: 'var(--ds-font-size-4xl)',
      fontWeight: 'var(--ds-font-weight-bold)',
      lineHeight: 'var(--ds-line-height-tight)',
    },
    'heading-2xl': {
      fontFamily: 'var(--ds-font-family-sans)',
      fontSize: 'var(--ds-font-size-5xl)',
      fontWeight: 'var(--ds-font-weight-bold)',
      lineHeight: 'var(--ds-line-height-tight)',
    },
    'body-xs': {
      fontFamily: 'var(--ds-font-family-sans)',
      fontSize: 'var(--ds-font-size-xs)',
      fontWeight: 'var(--ds-font-weight-normal)',
      lineHeight: 'var(--ds-line-height-normal)',
    },
    'body-sm': {
      fontFamily: 'var(--ds-font-family-sans)',
      fontSize: 'var(--ds-font-size-sm)',
      fontWeight: 'var(--ds-font-weight-normal)',
      lineHeight: 'var(--ds-line-height-normal)',
    },
    'body-md': {
      fontFamily: 'var(--ds-font-family-sans)',
      fontSize: 'var(--ds-font-size-base)',
      fontWeight: 'var(--ds-font-weight-normal)',
      lineHeight: 'var(--ds-line-height-normal)',
    },
    'body-lg': {
      fontFamily: 'var(--ds-font-family-sans)',
      fontSize: 'var(--ds-font-size-lg)',
      fontWeight: 'var(--ds-font-weight-normal)',
      lineHeight: 'var(--ds-line-height-relaxed)',
    },
    'label-sm': {
      fontFamily: 'var(--ds-font-family-sans)',
      fontSize: 'var(--ds-font-size-xs)',
      fontWeight: 'var(--ds-font-weight-medium)',
      lineHeight: 'var(--ds-line-height-normal)',
    },
    'label-md': {
      fontFamily: 'var(--ds-font-family-sans)',
      fontSize: 'var(--ds-font-size-sm)',
      fontWeight: 'var(--ds-font-weight-medium)',
      lineHeight: 'var(--ds-line-height-normal)',
    },
    'label-lg': {
      fontFamily: 'var(--ds-font-family-sans)',
      fontSize: 'var(--ds-font-size-base)',
      fontWeight: 'var(--ds-font-weight-medium)',
      lineHeight: 'var(--ds-line-height-normal)',
    },
    'code-sm': {
      fontFamily: 'var(--ds-font-family-mono)',
      fontSize: 'var(--ds-font-size-xs)',
      fontWeight: 'var(--ds-font-weight-normal)',
      lineHeight: 'var(--ds-line-height-normal)',
    },
    'code-md': {
      fontFamily: 'var(--ds-font-family-mono)',
      fontSize: 'var(--ds-font-size-sm)',
      fontWeight: 'var(--ds-font-weight-normal)',
      lineHeight: 'var(--ds-line-height-normal)',
    },
  },
} as const;

// Type exports for autocomplete
export type ColorToken = keyof typeof tokens.color;
export type SemanticGroup = keyof typeof tokens.semantic;
export type SpaceToken = keyof typeof tokens.space;
export type FontSizeToken = keyof typeof tokens.font.size;
export type FontWeightToken = keyof typeof tokens.font.weight;
export type LineHeightToken = keyof typeof tokens.font.lineHeight;
export type TrackingToken = keyof typeof tokens.tracking;
export type RadiusToken = keyof typeof tokens.radius;
export type ShadowToken = keyof typeof tokens.shadow;
export type ZIndexToken = keyof typeof tokens.zIndex;
export type BreakpointToken = keyof typeof tokens.breakpoint;
export type TypographyToken = keyof typeof tokens.typography;

// Resolve a token by dot-path (e.g. "semantic.primary.default").
export function getToken(path: string): string {
  const parts = path.split('.');
  let value: unknown = tokens;
  for (const part of parts) {
    if (value && typeof value === 'object' && part in value) {
      value = (value as Record<string, unknown>)[part];
    } else {
      console.warn(`Token not found: ${path}`);
      return '';
    }
  }
  return typeof value === 'string' ? value : '';
}

// Convert a camelCase style object to kebab-case CSS keys.
export function css(styles: Record<string, string | number>) {
  return Object.entries(styles).reduce(
    (acc, [key, value]) => {
      const cssKey = key.replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`);
      return { ...acc, [cssKey]: value };
    },
    {} as Record<string, string | number>,
  );
}
